// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainContainer = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_MainContainer);
    lv_obj_set_width(ui_MainContainer, lv_pct(100));
    lv_obj_set_height(ui_MainContainer, lv_pct(100));
    lv_obj_set_align(ui_MainContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MainContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MainContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_MainContainer, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_MainContainer, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_MainContainer, LV_DIR_HOR);

    ui_NowContainer = lv_obj_create(ui_MainContainer);
    lv_obj_remove_style_all(ui_NowContainer);
    lv_obj_set_width(ui_NowContainer, lv_pct(45));
    lv_obj_set_height(ui_NowContainer, lv_pct(90));
    lv_obj_set_x(ui_NowContainer, 0);
    lv_obj_set_y(ui_NowContainer, 6);
    lv_obj_set_align(ui_NowContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_NowContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_NowContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NowContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_NowContainer);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, lv_pct(90));
    lv_obj_set_height(ui_Container7, lv_pct(15));
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnLocal = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_BtnLocal, lv_pct(50));
    lv_obj_set_height(ui_BtnLocal, lv_pct(100));
    lv_obj_set_align(ui_BtnLocal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnLocal, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLocal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnLocal, lv_color_hex(0x2E6BE2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnLocal, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabLocal = lv_label_create(ui_BtnLocal);
    lv_obj_set_width(ui_LabLocal, lv_pct(150));
    lv_obj_set_height(ui_LabLocal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabLocal, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabLocal, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabLocal, "西青");
    lv_obj_set_style_text_align(ui_LabLocal, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabLocal, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabWeather = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_LabWeather, lv_pct(50));
    lv_obj_set_height(ui_LabWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabWeather, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabWeather, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabWeather, "优");
    lv_obj_set_style_text_align(ui_LabWeather, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabWeather, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_NowContainer);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_height(ui_Container9, lv_pct(15));
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabWind = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_LabWind, lv_pct(65));
    lv_obj_set_height(ui_LabWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabWind, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabWind, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabWind, "东北风10级 风速30m/s");
    lv_obj_set_style_text_align(ui_LabWind, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabWind, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnWifi = lv_btn_create(ui_Container9);
    lv_obj_set_width(ui_BtnWifi, lv_pct(16));
    lv_obj_set_height(ui_BtnWifi, lv_pct(75));
    lv_obj_set_align(ui_BtnWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnWifi, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgWifiStatus = lv_img_create(ui_BtnWifi);
    lv_img_set_src(ui_ImgWifiStatus, &ui_img_icon_discon_wifi_24_png);
    lv_obj_set_width(ui_ImgWifiStatus, 24);
    lv_obj_set_height(ui_ImgWifiStatus, 24);
    lv_obj_set_align(ui_ImgWifiStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWifiStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWifiStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container8 = lv_obj_create(ui_NowContainer);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(90));
    lv_obj_set_height(ui_Container8, lv_pct(25));
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabTime = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_LabTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabTime, -12);
    lv_obj_set_y(ui_LabTime, 5);
    lv_obj_set_align(ui_LabTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabTime, "20:00");
    lv_obj_set_style_text_font(ui_LabTime, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_NowContainer);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, lv_pct(100));
    lv_obj_set_height(ui_Container10, lv_pct(15));
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabDate = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_LabDate, lv_pct(65));
    lv_obj_set_height(ui_LabDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabDate, "2025-01-16");
    lv_obj_set_style_text_align(ui_LabDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabDate, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabWeek = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_LabWeek, lv_pct(30));
    lv_obj_set_height(ui_LabWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabWeek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabWeek, "周四");
    lv_obj_set_style_text_align(ui_LabWeek, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabWeek, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_NowContainer);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, lv_pct(95));
    lv_obj_set_height(ui_Container11, lv_pct(15));
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgTemp = lv_img_create(ui_Container11);
    lv_img_set_src(ui_ImgTemp, &ui_img_img_temp_30_png);
    lv_obj_set_width(ui_ImgTemp, 30);
    lv_obj_set_height(ui_ImgTemp, 30);
    lv_obj_set_align(ui_ImgTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarTemp = lv_bar_create(ui_Container11);
    lv_bar_set_range(ui_BarTemp, -20, 100);
    lv_bar_set_value(ui_BarTemp, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarTemp, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_BarTemp, 10);
    lv_obj_set_width(ui_BarTemp, lv_pct(50));
    lv_obj_set_x(ui_BarTemp, -63);
    lv_obj_set_y(ui_BarTemp, 59);
    lv_obj_set_align(ui_BarTemp, LV_ALIGN_CENTER);

    ui_LabTemp = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_LabTemp, 45);
    lv_obj_set_height(ui_LabTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabTemp, "22℃");
    lv_obj_set_style_text_align(ui_LabTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabTemp, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_NowContainer);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, lv_pct(95));
    lv_obj_set_height(ui_Container12, lv_pct(15));
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgHumi = lv_img_create(ui_Container12);
    lv_img_set_src(ui_ImgHumi, &ui_img_img_humi_30_png);
    lv_obj_set_width(ui_ImgHumi, 30);
    lv_obj_set_height(ui_ImgHumi, 30);
    lv_obj_set_align(ui_ImgHumi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgHumi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgHumi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarHumi = lv_bar_create(ui_Container12);
    lv_bar_set_value(ui_BarHumi, 45, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarHumi, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_BarHumi, 10);
    lv_obj_set_width(ui_BarHumi, lv_pct(50));
    lv_obj_set_align(ui_BarHumi, LV_ALIGN_CENTER);

    ui_LabHumi = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_LabHumi, 45);
    lv_obj_set_height(ui_LabHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabHumi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabHumi, "100%");
    lv_obj_set_style_text_align(ui_LabHumi, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabHumi, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FutureContainer = lv_obj_create(ui_MainContainer);
    lv_obj_remove_style_all(ui_FutureContainer);
    lv_obj_set_width(ui_FutureContainer, lv_pct(45));
    lv_obj_set_height(ui_FutureContainer, lv_pct(90));
    lv_obj_set_x(ui_FutureContainer, -322);
    lv_obj_set_y(ui_FutureContainer, 19);
    lv_obj_set_align(ui_FutureContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FutureContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FutureContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_FutureContainer, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_FutureContainer, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_FutureContainer, LV_DIR_HOR);

    ui_FirstContainer = lv_obj_create(ui_FutureContainer);
    lv_obj_remove_style_all(ui_FirstContainer);
    lv_obj_set_width(ui_FirstContainer, lv_pct(48));
    lv_obj_set_height(ui_FirstContainer, lv_pct(100));
    lv_obj_set_x(ui_FirstContainer, 64);
    lv_obj_set_y(ui_FirstContainer, -53);
    lv_obj_set_align(ui_FirstContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FirstContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FirstContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FirstContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnFirst = lv_btn_create(ui_FirstContainer);
    lv_obj_set_width(ui_BtnFirst, lv_pct(90));
    lv_obj_set_height(ui_BtnFirst, lv_pct(15));
    lv_obj_set_align(ui_BtnFirst, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BtnFirst, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabFirWeek = lv_label_create(ui_BtnFirst);
    lv_obj_set_width(ui_LabFirWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabFirWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabFirWeek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabFirWeek, "周四");
    lv_obj_set_style_text_align(ui_LabFirWeek, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabFirWeek, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabFirDate = lv_label_create(ui_FirstContainer);
    lv_obj_set_width(ui_LabFirDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabFirDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabFirDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabFirDate, "1-16");
    lv_obj_set_style_text_align(ui_LabFirDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabFirDate, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgFirWeather = lv_img_create(ui_FirstContainer);
    lv_img_set_src(ui_ImgFirWeather, &ui_img_icon_101_64_png);
    lv_obj_set_width(ui_ImgFirWeather, 64);
    lv_obj_set_height(ui_ImgFirWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgFirWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgFirWeather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgFirWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_ImgFirWeather, 9);
    lv_obj_set_style_img_recolor(ui_ImgFirWeather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgFirWeather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabFirTemp = lv_label_create(ui_FirstContainer);
    lv_obj_set_width(ui_LabFirTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabFirTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabFirTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabFirTemp, "-15~-4");
    lv_obj_set_style_text_align(ui_LabFirTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabFirTemp, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabFirWeather = lv_label_create(ui_FirstContainer);
    lv_obj_set_width(ui_LabFirWeather, lv_pct(100));
    lv_obj_set_height(ui_LabFirWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabFirWeather, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabFirWeather, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabFirWeather, "多云");
    lv_obj_set_style_text_align(ui_LabFirWeather, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabFirWeather, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabFirWind = lv_label_create(ui_FirstContainer);
    lv_obj_set_width(ui_LabFirWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabFirWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabFirWind, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabFirWind, "东北风");
    lv_obj_set_style_text_align(ui_LabFirWind, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabFirWind, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecondContainer = lv_obj_create(ui_FutureContainer);
    lv_obj_remove_style_all(ui_SecondContainer);
    lv_obj_set_width(ui_SecondContainer, lv_pct(48));
    lv_obj_set_height(ui_SecondContainer, lv_pct(100));
    lv_obj_set_x(ui_SecondContainer, 46);
    lv_obj_set_y(ui_SecondContainer, -15);
    lv_obj_set_align(ui_SecondContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SecondContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SecondContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_SecondContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnSecond = lv_btn_create(ui_SecondContainer);
    lv_obj_set_width(ui_BtnSecond, lv_pct(90));
    lv_obj_set_height(ui_BtnSecond, lv_pct(15));
    lv_obj_set_align(ui_BtnSecond, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BtnSecond, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabSecWeek = lv_label_create(ui_BtnSecond);
    lv_obj_set_width(ui_LabSecWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabSecWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabSecWeek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabSecWeek, "周五");
    lv_obj_set_style_text_align(ui_LabSecWeek, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabSecWeek, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabSecDate = lv_label_create(ui_SecondContainer);
    lv_obj_set_width(ui_LabSecDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabSecDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabSecDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabSecDate, "1-17");
    lv_obj_set_style_text_align(ui_LabSecDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabSecDate, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgSecWeather = lv_img_create(ui_SecondContainer);
    lv_img_set_src(ui_ImgSecWeather, &ui_img_icon_100_64_png);
    lv_obj_set_width(ui_ImgSecWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgSecWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgSecWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgSecWeather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgSecWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabSecTemp = lv_label_create(ui_SecondContainer);
    lv_obj_set_width(ui_LabSecTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabSecTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabSecTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabSecTemp, "-11~2");
    lv_obj_set_style_text_align(ui_LabSecTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabSecTemp, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabSecWeather = lv_label_create(ui_SecondContainer);
    lv_obj_set_width(ui_LabSecWeather, lv_pct(100));
    lv_obj_set_height(ui_LabSecWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabSecWeather, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabSecWeather, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabSecWeather, "晴");
    lv_obj_set_style_text_align(ui_LabSecWeather, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabSecWeather, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabSecWind = lv_label_create(ui_SecondContainer);
    lv_obj_set_width(ui_LabSecWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabSecWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabSecWind, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabSecWind, "西北风");
    lv_obj_set_style_text_align(ui_LabSecWind, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabSecWind, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThirdContainer = lv_obj_create(ui_FutureContainer);
    lv_obj_remove_style_all(ui_ThirdContainer);
    lv_obj_set_width(ui_ThirdContainer, lv_pct(48));
    lv_obj_set_height(ui_ThirdContainer, lv_pct(100));
    lv_obj_set_x(ui_ThirdContainer, 64);
    lv_obj_set_y(ui_ThirdContainer, 33);
    lv_obj_set_align(ui_ThirdContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ThirdContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ThirdContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_ThirdContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnThird = lv_btn_create(ui_ThirdContainer);
    lv_obj_set_width(ui_BtnThird, lv_pct(90));
    lv_obj_set_height(ui_BtnThird, lv_pct(15));
    lv_obj_set_align(ui_BtnThird, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnThird, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnThird, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabThiWeek = lv_label_create(ui_BtnThird);
    lv_obj_set_width(ui_LabThiWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabThiWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabThiWeek, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabThiWeek, "周六");
    lv_obj_set_style_text_align(ui_LabThiWeek, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabThiWeek, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabThiDate = lv_label_create(ui_ThirdContainer);
    lv_obj_set_width(ui_LabThiDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabThiDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabThiDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabThiDate, "1-18");
    lv_obj_set_style_text_align(ui_LabThiDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabThiDate, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgThiWeather = lv_img_create(ui_ThirdContainer);
    lv_img_set_src(ui_ImgThiWeather, &ui_img_icon_100_64_png);
    lv_obj_set_width(ui_ImgThiWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgThiWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgThiWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgThiWeather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgThiWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabThiTemp = lv_label_create(ui_ThirdContainer);
    lv_obj_set_width(ui_LabThiTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabThiTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabThiTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabThiTemp, "-11~5");
    lv_obj_set_style_text_align(ui_LabThiTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabThiTemp, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabThiWeather = lv_label_create(ui_ThirdContainer);
    lv_obj_set_width(ui_LabThiWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabThiWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabThiWeather, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabThiWeather, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabThiWeather, "晴");
    lv_obj_set_style_text_align(ui_LabThiWeather, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabThiWeather, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabThiWind = lv_label_create(ui_ThirdContainer);
    lv_obj_set_width(ui_LabThiWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabThiWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabThiWind, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabThiWind, "西风");
    lv_obj_set_style_text_align(ui_LabThiWind, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabThiWind, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnLocal, ui_event_BtnLocal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnWifi, ui_event_BtnWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnFirst, ui_event_BtnFirst, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSecond, ui_event_BtnSecond, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnThird, ui_event_BtnThird, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}
