// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SetLocalScreen_screen_init(void)
{
    ui_SetLocalScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SetLocalScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainContainer1 = lv_obj_create(ui_SetLocalScreen);
    lv_obj_remove_style_all(ui_MainContainer1);
    lv_obj_set_width(ui_MainContainer1, lv_pct(100));
    lv_obj_set_height(ui_MainContainer1, lv_pct(100));
    lv_obj_set_align(ui_MainContainer1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MainContainer1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MainContainer1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_MainContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_MainContainer1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, lv_pct(15));
    lv_obj_set_x(ui_Container2, -54);
    lv_obj_set_y(ui_Container2, -41);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack1 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_BtnBack1, lv_pct(10));
    lv_obj_set_height(ui_BtnBack1, lv_pct(100));
    lv_obj_set_x(ui_BtnBack1, -140);
    lv_obj_set_y(ui_BtnBack1, 0);
    lv_obj_set_align(ui_BtnBack1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnBack1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBack1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBack1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBack1 = lv_img_create(ui_BtnBack1);
    lv_img_set_src(ui_ImgBack1, &ui_img_icon_back_24_png);
    lv_obj_set_width(ui_ImgBack1, 24);
    lv_obj_set_height(ui_ImgBack1, 24);
    lv_obj_set_align(ui_ImgBack1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBack1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBack1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "配置城市");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_MainContainer1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_height(ui_Container3, lv_pct(85));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_height(ui_Container4, lv_pct(20));
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, -1);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_Container4);
    lv_dropdown_set_options(ui_Dropdown1,
                            "北京\n上海\n天津\n重庆\n黑龙江\n吉林\n辽宁\n内蒙古自治区\n河北\n山西\n陕西\n山东\n新疆维吾尔族自治区\n西藏自治区\n青海\n甘肃\n宁夏回族自治区\n河南\n江苏\n湖北\n浙江\n安徽\n福建\n江西\n湖南\n贵州\n四川\n广东\n云南\n广西壮族自治区\n海南\n香港特别行政区\n澳门特别行政区\n台湾");
    lv_obj_set_width(ui_Dropdown1, 120);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Dropdown1, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_Dropdown1), LV_TEXT_ALIGN_CENTER,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown1), &ui_font_Font20,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TaLocal = lv_textarea_create(ui_Container4);
    lv_obj_set_width(ui_TaLocal, 140);
    lv_obj_set_height(ui_TaLocal, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_TaLocal, -23);
    lv_obj_set_y(ui_TaLocal, -33);
    lv_obj_set_align(ui_TaLocal, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TaLocal, 50);
    lv_textarea_set_placeholder_text(ui_TaLocal, "chaoyang");
    lv_textarea_set_one_line(ui_TaLocal, true);
    lv_obj_set_style_text_align(ui_TaLocal, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_BtnSearchCity = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_BtnSearchCity, 30);
    lv_obj_set_height(ui_BtnSearchCity, 30);
    lv_obj_set_align(ui_BtnSearchCity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSearchCity, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSearchCity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSearchCity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSearchCity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_BtnSearchCity);
    lv_img_set_src(ui_Image1, &ui_img_icon_search_24_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container20 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_height(ui_Container20, 26);
    lv_obj_set_width(ui_Container20, lv_pct(100));
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabInformation = lv_label_create(ui_Container20);
    lv_obj_set_height(ui_LabInformation, 25);
    lv_obj_set_width(ui_LabInformation, lv_pct(100));
    lv_obj_set_align(ui_LabInformation, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabInformation, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabInformation, "未能搜索到城市");
    lv_obj_add_flag(ui_LabInformation, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_align(ui_LabInformation, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabInformation, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Container3);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_height(ui_Container5, lv_pct(70));
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerCityLeft = lv_obj_create(ui_Container5);
    lv_obj_remove_style_all(ui_ContainerCityLeft);
    lv_obj_set_width(ui_ContainerCityLeft, lv_pct(45));
    lv_obj_set_height(ui_ContainerCityLeft, lv_pct(90));
    lv_obj_set_align(ui_ContainerCityLeft, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerCityLeft, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerCityLeft, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerCityLeft, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerCityLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabCity1 = lv_label_create(ui_ContainerCityLeft);
    lv_obj_set_width(ui_LabCity1, lv_pct(100));
    lv_obj_set_height(ui_LabCity1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabCity1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabCity1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabCity1, "城市(区):");
    lv_obj_set_style_text_font(ui_LabCity1, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabSuperiorCity1 = lv_label_create(ui_ContainerCityLeft);
    lv_obj_set_width(ui_LabSuperiorCity1, lv_pct(100));
    lv_obj_set_height(ui_LabSuperiorCity1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabSuperiorCity1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabSuperiorCity1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabSuperiorCity1, "上级行政区:");
    lv_obj_set_style_text_font(ui_LabSuperiorCity1, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSearch1 = lv_btn_create(ui_ContainerCityLeft);
    lv_obj_set_width(ui_BtnSearch1, 35);
    lv_obj_set_height(ui_BtnSearch1, 35);
    lv_obj_set_align(ui_BtnSearch1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSearch1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSearch1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSearch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSearch1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_BtnSearch1);
    lv_img_set_src(ui_Image3, &ui_img_icon_choose_32_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerCityRight = lv_obj_create(ui_Container5);
    lv_obj_remove_style_all(ui_ContainerCityRight);
    lv_obj_set_width(ui_ContainerCityRight, lv_pct(45));
    lv_obj_set_height(ui_ContainerCityRight, lv_pct(90));
    lv_obj_set_align(ui_ContainerCityRight, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerCityRight, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerCityRight, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerCityRight, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerCityRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabCity2 = lv_label_create(ui_ContainerCityRight);
    lv_obj_set_width(ui_LabCity2, lv_pct(100));
    lv_obj_set_height(ui_LabCity2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabCity2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabCity2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabCity2, "城市(区):");
    lv_obj_set_style_text_font(ui_LabCity2, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabSuperiorCity2 = lv_label_create(ui_ContainerCityRight);
    lv_obj_set_width(ui_LabSuperiorCity2, lv_pct(100));
    lv_obj_set_height(ui_LabSuperiorCity2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabSuperiorCity2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabSuperiorCity2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabSuperiorCity2, "上级行政区:");
    lv_obj_set_style_text_font(ui_LabSuperiorCity2, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSearch2 = lv_btn_create(ui_ContainerCityRight);
    lv_obj_set_width(ui_BtnSearch2, 35);
    lv_obj_set_height(ui_BtnSearch2, 35);
    lv_obj_set_align(ui_BtnSearch2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSearch2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSearch2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSearch2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSearch2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_BtnSearch2);
    lv_img_set_src(ui_Image4, &ui_img_icon_choose_32_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeybLocal = lv_keyboard_create(ui_SetLocalScreen);
    lv_obj_set_height(ui_KeybLocal, 120);
    lv_obj_set_width(ui_KeybLocal, lv_pct(100));
    lv_obj_set_x(ui_KeybLocal, 0);
    lv_obj_set_y(ui_KeybLocal, 55);
    lv_obj_set_align(ui_KeybLocal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeybLocal, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_BtnBack1, ui_event_BtnBack1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TaLocal, ui_event_TaLocal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSearchCity, ui_event_BtnSearchCity, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSearch1, ui_event_BtnSearch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSearch2, ui_event_BtnSearch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetLocalScreen, ui_event_SetLocalScreen, LV_EVENT_ALL, NULL);

}
