// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SetWifiScreen_screen_init(void)
{
    ui_SetWifiScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SetWifiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainContainer3 = lv_obj_create(ui_SetWifiScreen);
    lv_obj_remove_style_all(ui_MainContainer3);
    lv_obj_set_width(ui_MainContainer3, lv_pct(100));
    lv_obj_set_height(ui_MainContainer3, lv_pct(100));
    lv_obj_set_align(ui_MainContainer3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MainContainer3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MainContainer3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_MainContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container19 = lv_obj_create(ui_MainContainer3);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, lv_pct(100));
    lv_obj_set_height(ui_Container19, lv_pct(15));
    lv_obj_set_x(ui_Container19, -54);
    lv_obj_set_y(ui_Container19, -41);
    lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container19, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container19, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack2 = lv_btn_create(ui_Container19);
    lv_obj_set_width(ui_BtnBack2, lv_pct(10));
    lv_obj_set_height(ui_BtnBack2, lv_pct(100));
    lv_obj_set_x(ui_BtnBack2, -140);
    lv_obj_set_y(ui_BtnBack2, 0);
    lv_obj_set_align(ui_BtnBack2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnBack2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBack2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBack2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBack2 = lv_img_create(ui_BtnBack2);
    lv_img_set_src(ui_ImgBack2, &ui_img_icon_back_24_png);
    lv_obj_set_width(ui_ImgBack2, 24);
    lv_obj_set_height(ui_ImgBack2, 24);
    lv_obj_set_align(ui_ImgBack2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBack2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBack2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Container19);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "WiFi配置");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgWifiStatus2 = lv_img_create(ui_Container19);
    lv_img_set_src(ui_ImgWifiStatus2, &ui_img_icon_discon_wifi_24_png);
    lv_obj_set_width(ui_ImgWifiStatus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgWifiStatus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgWifiStatus2, 140);
    lv_obj_set_y(ui_ImgWifiStatus2, 0);
    lv_obj_set_align(ui_ImgWifiStatus2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWifiStatus2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWifiStatus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_MainContainer3);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, lv_pct(85));
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container14 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, lv_pct(100));
    lv_obj_set_height(ui_Container14, lv_pct(20));
    lv_obj_set_x(ui_Container14, 0);
    lv_obj_set_y(ui_Container14, -1);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DropdownWifi = lv_dropdown_create(ui_Container14);
    lv_dropdown_set_options(ui_DropdownWifi, "CMCC-\nTP-LINK-\nXiaomi");
    lv_obj_set_width(ui_DropdownWifi, 120);
    lv_obj_set_height(ui_DropdownWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownWifi, -1);
    lv_obj_set_y(ui_DropdownWifi, 9);
    lv_obj_set_align(ui_DropdownWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_text_font(ui_DropdownWifi, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_BtnRefreshWifi = lv_btn_create(ui_Container14);
    lv_obj_set_width(ui_BtnRefreshWifi, 30);
    lv_obj_set_height(ui_BtnRefreshWifi, 30);
    lv_obj_set_align(ui_BtnRefreshWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnRefreshWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnRefreshWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnRefreshWifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnRefreshWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_BtnRefreshWifi);
    lv_img_set_src(ui_Image2, &ui_img_icon_refresh_24_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TaWifiPassword = lv_textarea_create(ui_Container14);
    lv_obj_set_width(ui_TaWifiPassword, 120);
    lv_obj_set_height(ui_TaWifiPassword, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_TaWifiPassword, -23);
    lv_obj_set_y(ui_TaWifiPassword, -33);
    lv_obj_set_align(ui_TaWifiPassword, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TaWifiPassword, 50);
    lv_textarea_set_placeholder_text(ui_TaWifiPassword, "password");
    lv_textarea_set_one_line(ui_TaWifiPassword, true);
    lv_textarea_set_password_mode(ui_TaWifiPassword, true);
    lv_obj_set_style_text_align(ui_TaWifiPassword, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_SwiWifi = lv_switch_create(ui_Container14);
    lv_obj_set_width(ui_SwiWifi, 50);
    lv_obj_set_height(ui_SwiWifi, 25);
    lv_obj_set_x(ui_SwiWifi, 130);
    lv_obj_set_y(ui_SwiWifi, 0);
    lv_obj_set_align(ui_SwiWifi, LV_ALIGN_CENTER);


    ui_Container13 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, lv_pct(100));
    lv_obj_set_height(ui_Container13, lv_pct(15));
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabWifiInformation = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_LabWifiInformation, lv_pct(100));
    lv_obj_set_height(ui_LabWifiInformation, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_LabWifiInformation, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabWifiInformation, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabWifiInformation, "当前连接WiFi: CMCC-4qfy-12");
    lv_obj_set_style_text_align(ui_LabWifiInformation, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabWifiInformation, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, lv_pct(100));
    lv_obj_set_height(ui_Container15, lv_pct(70));
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container16 = lv_obj_create(ui_Container15);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, lv_pct(45));
    lv_obj_set_height(ui_Container16, lv_pct(90));
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container17 = lv_obj_create(ui_Container15);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_width(ui_Container17, lv_pct(45));
    lv_obj_set_height(ui_Container17, lv_pct(90));
    lv_obj_set_align(ui_Container17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard2 = lv_keyboard_create(ui_SetWifiScreen);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_width(ui_Keyboard2, lv_pct(100));
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 54);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_BtnBack2, ui_event_BtnBack2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnRefreshWifi, ui_event_BtnRefreshWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TaWifiPassword, ui_event_TaWifiPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwiWifi, ui_event_SwiWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetWifiScreen, ui_event_SetWifiScreen, LV_EVENT_ALL, NULL);

}
