// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_WeatherScreen_screen_init(void)
{
    ui_WeatherScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WeatherScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainContainer4 = lv_obj_create(ui_WeatherScreen);
    lv_obj_remove_style_all(ui_MainContainer4);
    lv_obj_set_width(ui_MainContainer4, lv_pct(100));
    lv_obj_set_height(ui_MainContainer4, lv_pct(100));
    lv_obj_set_align(ui_MainContainer4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MainContainer4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MainContainer4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_MainContainer4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container25 = lv_obj_create(ui_MainContainer4);
    lv_obj_remove_style_all(ui_Container25);
    lv_obj_set_width(ui_Container25, lv_pct(100));
    lv_obj_set_height(ui_Container25, lv_pct(15));
    lv_obj_set_x(ui_Container25, -54);
    lv_obj_set_y(ui_Container25, -41);
    lv_obj_set_align(ui_Container25, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container25, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container25, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack4 = lv_btn_create(ui_Container25);
    lv_obj_set_width(ui_BtnBack4, lv_pct(10));
    lv_obj_set_height(ui_BtnBack4, lv_pct(100));
    lv_obj_set_x(ui_BtnBack4, -140);
    lv_obj_set_y(ui_BtnBack4, 0);
    lv_obj_set_align(ui_BtnBack4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnBack4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnBack4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnBack4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBack4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBack4 = lv_img_create(ui_BtnBack4);
    lv_img_set_src(ui_ImgBack4, &ui_img_icon_back_24_png);
    lv_obj_set_width(ui_ImgBack4, 24);
    lv_obj_set_height(ui_ImgBack4, 24);
    lv_obj_set_align(ui_ImgBack4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBack4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBack4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Container25);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "天气信息");
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabRefreshTime = lv_label_create(ui_Container25);
    lv_obj_set_width(ui_LabRefreshTime, 65);
    lv_obj_set_height(ui_LabRefreshTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabRefreshTime, 110);
    lv_obj_set_y(ui_LabRefreshTime, 0);
    lv_obj_set_align(ui_LabRefreshTime, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabRefreshTime, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabRefreshTime, "最后一次刷新时间 2025-01-24 18:30");
    lv_obj_set_style_text_color(ui_LabRefreshTime, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabRefreshTime, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabRefreshTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabRefreshTime, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container26 = lv_obj_create(ui_MainContainer4);
    lv_obj_remove_style_all(ui_Container26);
    lv_obj_set_width(ui_Container26, lv_pct(100));
    lv_obj_set_height(ui_Container26, lv_pct(26));
    lv_obj_set_align(ui_Container26, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container26, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container26, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container26, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabDailyDate = lv_label_create(ui_Container26);
    lv_obj_set_width(ui_LabDailyDate, 150);
    lv_obj_set_height(ui_LabDailyDate, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_LabDailyDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabDailyDate, "2025-01-17");
    lv_obj_set_style_text_align(ui_LabDailyDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabDailyDate, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabPhaseMoon = lv_label_create(ui_Container26);
    lv_obj_set_width(ui_LabPhaseMoon, 64);
    lv_obj_set_height(ui_LabPhaseMoon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabPhaseMoon, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabPhaseMoon, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabPhaseMoon, "峨眉月");
    lv_obj_set_style_text_align(ui_LabPhaseMoon, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabPhaseMoon, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgPhaseMoon = lv_img_create(ui_Container26);
    lv_img_set_src(ui_ImgPhaseMoon, &ui_img_icon_first_quarter_half_moon_36_png);
    lv_obj_set_width(ui_ImgPhaseMoon, 36);
    lv_obj_set_height(ui_ImgPhaseMoon, 36);
    lv_obj_set_align(ui_ImgPhaseMoon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgPhaseMoon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgPhaseMoon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container18 = lv_obj_create(ui_MainContainer4);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, lv_pct(100));
    lv_obj_set_height(ui_Container18, lv_pct(64));
    lv_obj_set_align(ui_Container18, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container18, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container18, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container6 = lv_obj_create(ui_Container18);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(47));
    lv_obj_set_height(ui_Container6, lv_pct(100));
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container21 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_height(ui_Container21, 65);
    lv_obj_set_width(ui_Container21, lv_pct(100));
    lv_obj_set_align(ui_Container21, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container21, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container21, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgDayWeather = lv_img_create(ui_Container21);
    lv_img_set_src(ui_ImgDayWeather, &ui_img_icon_100_64_png);
    lv_obj_set_width(ui_ImgDayWeather, 64);
    lv_obj_set_height(ui_ImgDayWeather, 64);
    lv_obj_set_align(ui_ImgDayWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgDayWeather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgDayWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container23 = lv_obj_create(ui_Container21);
    lv_obj_remove_style_all(ui_Container23);
    lv_obj_set_width(ui_Container23, 96);
    lv_obj_set_height(ui_Container23, lv_pct(100));
    lv_obj_set_align(ui_Container23, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container23, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container23, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabDayWeather = lv_label_create(ui_Container23);
    lv_obj_set_height(ui_LabDayWeather, 32);
    lv_obj_set_width(ui_LabDayWeather, lv_pct(100));
    lv_obj_set_align(ui_LabDayWeather, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabDayWeather, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabDayWeather, "晴转多云 2℃");
    lv_obj_set_style_text_align(ui_LabDayWeather, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabDayWeather, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabDayWind = lv_label_create(ui_Container23);
    lv_obj_set_height(ui_LabDayWind, 32);
    lv_obj_set_width(ui_LabDayWind, lv_pct(100));
    lv_obj_set_align(ui_LabDayWind, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabDayWind, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabDayWind, "西北风 1-3级 风速: 3m/s");
    lv_obj_set_style_text_align(ui_LabDayWind, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabDayWind, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container22 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_height(ui_Container22, 55);
    lv_obj_set_width(ui_Container22, lv_pct(100));
    lv_obj_set_align(ui_Container22, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container22, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container22, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabSunrise = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_LabSunrise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabSunrise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabSunrise, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabSunrise, "日出  07:30");
    lv_obj_set_style_text_align(ui_LabSunrise, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabSunrise, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabSunset = lv_label_create(ui_Container22);
    lv_obj_set_width(ui_LabSunset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabSunset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabSunset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabSunset, "日落  20:46");
    lv_obj_set_style_text_align(ui_LabSunset, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabSunset, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container31 = lv_obj_create(ui_Container18);
    lv_obj_remove_style_all(ui_Container31);
    lv_obj_set_width(ui_Container31, lv_pct(47));
    lv_obj_set_height(ui_Container31, lv_pct(100));
    lv_obj_set_align(ui_Container31, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container31, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container31, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container31, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container27 = lv_obj_create(ui_Container31);
    lv_obj_remove_style_all(ui_Container27);
    lv_obj_set_height(ui_Container27, 64);
    lv_obj_set_width(ui_Container27, lv_pct(100));
    lv_obj_set_align(ui_Container27, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container27, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container27, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container27, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgNightWeather = lv_img_create(ui_Container27);
    lv_img_set_src(ui_ImgNightWeather, &ui_img_icon_102_64_png);
    lv_obj_set_width(ui_ImgNightWeather, 64);
    lv_obj_set_height(ui_ImgNightWeather, 64);
    lv_obj_set_align(ui_ImgNightWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgNightWeather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgNightWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container28 = lv_obj_create(ui_Container27);
    lv_obj_remove_style_all(ui_Container28);
    lv_obj_set_width(ui_Container28, 96);
    lv_obj_set_height(ui_Container28, lv_pct(100));
    lv_obj_set_align(ui_Container28, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container28, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container28, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_clear_flag(ui_Container28, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabMoonWeather = lv_label_create(ui_Container28);
    lv_obj_set_height(ui_LabMoonWeather, 32);
    lv_obj_set_width(ui_LabMoonWeather, lv_pct(100));
    lv_obj_set_align(ui_LabMoonWeather, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabMoonWeather, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabMoonWeather, "晴间多云 2℃");
    lv_obj_set_style_text_align(ui_LabMoonWeather, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabMoonWeather, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabMoonWind = lv_label_create(ui_Container28);
    lv_obj_set_height(ui_LabMoonWind, 32);
    lv_obj_set_width(ui_LabMoonWind, lv_pct(100));
    lv_obj_set_align(ui_LabMoonWind, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabMoonWind, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabMoonWind, "西北风 1-3级 风速: 3m/s");
    lv_obj_set_style_text_align(ui_LabMoonWind, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabMoonWind, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container29 = lv_obj_create(ui_Container31);
    lv_obj_remove_style_all(ui_Container29);
    lv_obj_set_height(ui_Container29, 55);
    lv_obj_set_width(ui_Container29, lv_pct(100));
    lv_obj_set_align(ui_Container29, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container29, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container29, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container29, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabMoonrise = lv_label_create(ui_Container29);
    lv_obj_set_width(ui_LabMoonrise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabMoonrise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabMoonrise, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabMoonrise, "月升  07:30");
    lv_obj_set_style_text_align(ui_LabMoonrise, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabMoonrise, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabMoonset = lv_label_create(ui_Container29);
    lv_obj_set_width(ui_LabMoonset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabMoonset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabMoonset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabMoonset, "月落  20:46");
    lv_obj_set_style_text_align(ui_LabMoonset, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabMoonset, &ui_font_Font20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBack4, ui_event_BtnBack4, LV_EVENT_ALL, NULL);

}
