// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_MainContainer;
lv_obj_t * ui_NowContainer;
lv_obj_t * ui_Container7;
void ui_event_BtnLocal(lv_event_t * e);
lv_obj_t * ui_BtnLocal;
lv_obj_t * ui_LabLocal;
lv_obj_t * ui_LabWeather;
lv_obj_t * ui_Container9;
lv_obj_t * ui_LabWind;
void ui_event_BtnWifi(lv_event_t * e);
lv_obj_t * ui_BtnWifi;
lv_obj_t * ui_ImgWifiStatus;
lv_obj_t * ui_Container8;
lv_obj_t * ui_LabTime;
lv_obj_t * ui_Container10;
lv_obj_t * ui_LabDate;
lv_obj_t * ui_LabWeek;
lv_obj_t * ui_Container11;
lv_obj_t * ui_ImgTemp;
lv_obj_t * ui_BarTemp;
lv_obj_t * ui_LabTemp;
lv_obj_t * ui_Container12;
lv_obj_t * ui_ImgHumi;
lv_obj_t * ui_BarHumi;
lv_obj_t * ui_LabHumi;
lv_obj_t * ui_FutureContainer;
lv_obj_t * ui_FirstContainer;
void ui_event_BtnFirst(lv_event_t * e);
lv_obj_t * ui_BtnFirst;
lv_obj_t * ui_LabFirWeek;
lv_obj_t * ui_LabFirDate;
lv_obj_t * ui_ImgFirWeather;
lv_obj_t * ui_LabFirTemp;
lv_obj_t * ui_LabFirWeather;
lv_obj_t * ui_LabFirWind;
lv_obj_t * ui_SecondContainer;
void ui_event_BtnSecond(lv_event_t * e);
lv_obj_t * ui_BtnSecond;
lv_obj_t * ui_LabSecWeek;
lv_obj_t * ui_LabSecDate;
lv_obj_t * ui_ImgSecWeather;
lv_obj_t * ui_LabSecTemp;
lv_obj_t * ui_LabSecWeather;
lv_obj_t * ui_LabSecWind;
lv_obj_t * ui_ThirdContainer;
void ui_event_BtnThird(lv_event_t * e);
lv_obj_t * ui_BtnThird;
lv_obj_t * ui_LabThiWeek;
lv_obj_t * ui_LabThiDate;
lv_obj_t * ui_ImgThiWeather;
lv_obj_t * ui_LabThiTemp;
lv_obj_t * ui_LabThiWeather;
lv_obj_t * ui_LabThiWind;


// SCREEN: ui_SetLocalScreen
void ui_SetLocalScreen_screen_init(void);
void ui_event_SetLocalScreen(lv_event_t * e);
lv_obj_t * ui_SetLocalScreen;
lv_obj_t * ui_MainContainer1;
lv_obj_t * ui_Container2;
void ui_event_BtnBack1(lv_event_t * e);
lv_obj_t * ui_BtnBack1;
lv_obj_t * ui_ImgBack1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Dropdown1;
void ui_event_TaLocal(lv_event_t * e);
lv_obj_t * ui_TaLocal;
void ui_event_BtnSearchCity(lv_event_t * e);
lv_obj_t * ui_BtnSearchCity;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Container20;
lv_obj_t * ui_LabInformation;
lv_obj_t * ui_Container5;
lv_obj_t * ui_ContainerCityLeft;
lv_obj_t * ui_LabCity1;
lv_obj_t * ui_LabSuperiorCity1;
void ui_event_BtnSearch1(lv_event_t * e);
lv_obj_t * ui_BtnSearch1;
lv_obj_t * ui_Image3;
lv_obj_t * ui_ContainerCityRight;
lv_obj_t * ui_LabCity2;
lv_obj_t * ui_LabSuperiorCity2;
void ui_event_BtnSearch2(lv_event_t * e);
lv_obj_t * ui_BtnSearch2;
lv_obj_t * ui_Image4;
lv_obj_t * ui_KeybLocal;


// SCREEN: ui_SetWifiScreen
void ui_SetWifiScreen_screen_init(void);
void ui_event_SetWifiScreen(lv_event_t * e);
lv_obj_t * ui_SetWifiScreen;
lv_obj_t * ui_MainContainer3;
lv_obj_t * ui_Container19;
void ui_event_BtnBack2(lv_event_t * e);
lv_obj_t * ui_BtnBack2;
lv_obj_t * ui_ImgBack2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_ImgWifiStatus2;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Container14;
lv_obj_t * ui_DropdownWifi;
void ui_event_BtnRefreshWifi(lv_event_t * e);
lv_obj_t * ui_BtnRefreshWifi;
lv_obj_t * ui_Image2;
void ui_event_TaWifiPassword(lv_event_t * e);
lv_obj_t * ui_TaWifiPassword;
void ui_event_SwiWifi(lv_event_t * e);
lv_obj_t * ui_SwiWifi;
lv_obj_t * ui_Container13;
lv_obj_t * ui_LabWifiInformation;
lv_obj_t * ui_Container15;
lv_obj_t * ui_Container16;
lv_obj_t * ui_Container17;
lv_obj_t * ui_Keyboard2;


// SCREEN: ui_WeatherScreen
void ui_WeatherScreen_screen_init(void);
lv_obj_t * ui_WeatherScreen;
lv_obj_t * ui_MainContainer4;
lv_obj_t * ui_Container25;
void ui_event_BtnBack4(lv_event_t * e);
lv_obj_t * ui_BtnBack4;
lv_obj_t * ui_ImgBack4;
lv_obj_t * ui_Label4;
lv_obj_t * ui_LabRefreshTime;
lv_obj_t * ui_Container26;
lv_obj_t * ui_LabDailyDate;
lv_obj_t * ui_LabPhaseMoon;
lv_obj_t * ui_ImgPhaseMoon;
lv_obj_t * ui_Container18;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Container21;
lv_obj_t * ui_ImgDayWeather;
lv_obj_t * ui_Container23;
lv_obj_t * ui_LabDayWeather;
lv_obj_t * ui_LabDayWind;
lv_obj_t * ui_Container22;
lv_obj_t * ui_LabSunrise;
lv_obj_t * ui_LabSunset;
lv_obj_t * ui_Container31;
lv_obj_t * ui_Container27;
lv_obj_t * ui_ImgNightWeather;
lv_obj_t * ui_Container28;
lv_obj_t * ui_LabMoonWeather;
lv_obj_t * ui_LabMoonWind;
lv_obj_t * ui_Container29;
lv_obj_t * ui_LabMoonrise;
lv_obj_t * ui_LabMoonset;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_icon_100_[1] = {&ui_img_icon_100_64_png};
const lv_img_dsc_t * ui_imgset_icon_101_[1] = {&ui_img_icon_101_64_png};
const lv_img_dsc_t * ui_imgset_icon_102_[1] = {&ui_img_icon_102_64_png};
const lv_img_dsc_t * ui_imgset_icon_103_[1] = {&ui_img_icon_103_64_png};
const lv_img_dsc_t * ui_imgset_icon_104_[1] = {&ui_img_icon_104_64_png};
const lv_img_dsc_t * ui_imgset_icon_150_[1] = {&ui_img_icon_150_64_png};
const lv_img_dsc_t * ui_imgset_icon_153_[1] = {&ui_img_icon_153_64_png};
const lv_img_dsc_t * ui_imgset_icon_154_[1] = {&ui_img_icon_154_64_png};
const lv_img_dsc_t * ui_imgset_icon_300_[1] = {&ui_img_icon_300_64_png};
const lv_img_dsc_t * ui_imgset_icon_301_[1] = {&ui_img_icon_301_64_png};
const lv_img_dsc_t * ui_imgset_icon_302_[1] = {&ui_img_icon_302_64_png};
const lv_img_dsc_t * ui_imgset_icon_303_[1] = {&ui_img_icon_303_64_png};
const lv_img_dsc_t * ui_imgset_icon_304_[1] = {&ui_img_icon_304_64_png};
const lv_img_dsc_t * ui_imgset_icon_305_[1] = {&ui_img_icon_305_64_png};
const lv_img_dsc_t * ui_imgset_icon_306_[1] = {&ui_img_icon_306_64_png};
const lv_img_dsc_t * ui_imgset_icon_307_[1] = {&ui_img_icon_307_64_png};
const lv_img_dsc_t * ui_imgset_icon_308_[1] = {&ui_img_icon_308_64_png};
const lv_img_dsc_t * ui_imgset_icon_309_[1] = {&ui_img_icon_309_64_png};
const lv_img_dsc_t * ui_imgset_icon_310_[1] = {&ui_img_icon_310_64_png};
const lv_img_dsc_t * ui_imgset_icon_311_[1] = {&ui_img_icon_311_64_png};
const lv_img_dsc_t * ui_imgset_icon_312_[1] = {&ui_img_icon_312_64_png};
const lv_img_dsc_t * ui_imgset_icon_313_[1] = {&ui_img_icon_313_64_png};
const lv_img_dsc_t * ui_imgset_icon_314_[1] = {&ui_img_icon_314_64_png};
const lv_img_dsc_t * ui_imgset_icon_315_[1] = {&ui_img_icon_315_64_png};
const lv_img_dsc_t * ui_imgset_icon_316_[1] = {&ui_img_icon_316_64_png};
const lv_img_dsc_t * ui_imgset_icon_317_[1] = {&ui_img_icon_317_64_png};
const lv_img_dsc_t * ui_imgset_icon_318_[1] = {&ui_img_icon_318_64_png};
const lv_img_dsc_t * ui_imgset_icon_350_[1] = {&ui_img_icon_350_64_png};
const lv_img_dsc_t * ui_imgset_icon_351_[1] = {&ui_img_icon_351_64_png};
const lv_img_dsc_t * ui_imgset_icon_399_[1] = {&ui_img_icon_399_64_png};
const lv_img_dsc_t * ui_imgset_icon_400_[1] = {&ui_img_icon_400_64_png};
const lv_img_dsc_t * ui_imgset_icon_401_[1] = {&ui_img_icon_401_64_png};
const lv_img_dsc_t * ui_imgset_icon_402_[1] = {&ui_img_icon_402_64_png};
const lv_img_dsc_t * ui_imgset_icon_403_[1] = {&ui_img_icon_403_64_png};
const lv_img_dsc_t * ui_imgset_icon_404_[1] = {&ui_img_icon_404_64_png};
const lv_img_dsc_t * ui_imgset_icon_405_[1] = {&ui_img_icon_405_64_png};
const lv_img_dsc_t * ui_imgset_icon_406_[1] = {&ui_img_icon_406_64_png};
const lv_img_dsc_t * ui_imgset_icon_407_[1] = {&ui_img_icon_407_64_png};
const lv_img_dsc_t * ui_imgset_icon_408_[1] = {&ui_img_icon_408_64_png};
const lv_img_dsc_t * ui_imgset_icon_409_[1] = {&ui_img_icon_409_64_png};
const lv_img_dsc_t * ui_imgset_icon_410_[1] = {&ui_img_icon_410_64_png};
const lv_img_dsc_t * ui_imgset_icon_456_[1] = {&ui_img_icon_456_64_png};
const lv_img_dsc_t * ui_imgset_icon_457_[1] = {&ui_img_icon_457_64_png};
const lv_img_dsc_t * ui_imgset_icon_499_[1] = {&ui_img_icon_499_64_png};
const lv_img_dsc_t * ui_imgset_icon_500_[1] = {&ui_img_icon_500_64_png};
const lv_img_dsc_t * ui_imgset_icon_501_[1] = {&ui_img_icon_501_64_png};
const lv_img_dsc_t * ui_imgset_icon_502_[1] = {&ui_img_icon_502_64_png};
const lv_img_dsc_t * ui_imgset_icon_503_[1] = {&ui_img_icon_503_64_png};
const lv_img_dsc_t * ui_imgset_icon_504_[1] = {&ui_img_icon_504_64_png};
const lv_img_dsc_t * ui_imgset_icon_507_[1] = {&ui_img_icon_507_64_png};
const lv_img_dsc_t * ui_imgset_icon_508_[1] = {&ui_img_icon_508_64_png};
const lv_img_dsc_t * ui_imgset_icon_509_[1] = {&ui_img_icon_509_64_png};
const lv_img_dsc_t * ui_imgset_icon_510_[1] = {&ui_img_icon_510_64_png};
const lv_img_dsc_t * ui_imgset_icon_511_[1] = {&ui_img_icon_511_64_png};
const lv_img_dsc_t * ui_imgset_icon_512_[1] = {&ui_img_icon_512_64_png};
const lv_img_dsc_t * ui_imgset_icon_513_[1] = {&ui_img_icon_513_64_png};
const lv_img_dsc_t * ui_imgset_icon_514_[1] = {&ui_img_icon_514_64_png};
const lv_img_dsc_t * ui_imgset_icon_515_[1] = {&ui_img_icon_515_64_png};
const lv_img_dsc_t * ui_imgset_icon_900_[1] = {&ui_img_icon_900_64_png};
const lv_img_dsc_t * ui_imgset_icon_901_[1] = {&ui_img_icon_901_64_png};
const lv_img_dsc_t * ui_imgset_icon_999_[1] = {&ui_img_icon_999_64_png};
const lv_img_dsc_t * ui_imgset_icon_back_[1] = {&ui_img_icon_back_24_png};
const lv_img_dsc_t * ui_imgset_icon_choose_[1] = {&ui_img_icon_choose_32_png};
const lv_img_dsc_t * ui_imgset_icon_connect_[1] = {&ui_img_icon_connect_24_png};
const lv_img_dsc_t * ui_imgset_icon_discon_wifi_[1] = {&ui_img_icon_discon_wifi_24_png};
const lv_img_dsc_t * ui_imgset_icon_first_quarter_half_moon_[1] = {&ui_img_icon_first_quarter_half_moon_36_png};
const lv_img_dsc_t * ui_imgset_icon_full_moon_[1] = {&ui_img_icon_full_moon_36_png};
const lv_img_dsc_t * ui_imgset_icon_last_quarter_half_moon_[1] = {&ui_img_icon_last_quarter_half_moon_36_png};
const lv_img_dsc_t * ui_imgset_icon_new_moon_[1] = {&ui_img_icon_new_moon_36_png};
const lv_img_dsc_t * ui_imgset_icon_refresh_[1] = {&ui_img_icon_refresh_24_png};
const lv_img_dsc_t * ui_imgset_icon_search_[1] = {&ui_img_icon_search_24_png};
const lv_img_dsc_t * ui_imgset_icon_waning_crescent_moon_[1] = {&ui_img_icon_waning_crescent_moon_36_png};
const lv_img_dsc_t * ui_imgset_icon_waning_gibbous_moon_[1] = {&ui_img_icon_waning_gibbous_moon_36_png};
const lv_img_dsc_t * ui_imgset_icon_waxing_crescent_moon_[1] = {&ui_img_icon_waxing_crescent_moon_36_png};
const lv_img_dsc_t * ui_imgset_icon_waxing_gibbous_moon_[1] = {&ui_img_icon_waxing_gibbous_moon_36_png};
const lv_img_dsc_t * ui_imgset_icon_wifi_[1] = {&ui_img_icon_wifi_24_png};
const lv_img_dsc_t * ui_imgset_img_humi_[1] = {&ui_img_img_humi_30_png};
const lv_img_dsc_t * ui_imgset_img_temp_[1] = {&ui_img_img_temp_30_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        init_ui_data(e);
    }
}
void ui_event_BtnLocal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_SetLocalScreen, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_SetLocalScreen_screen_init);
    }
}
void ui_event_BtnWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_SetWifiScreen, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_SetWifiScreen_screen_init);
    }
}
void ui_event_BtnFirst(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_WeatherScreen, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_WeatherScreen_screen_init);
        set_daily_information(e);
    }
}
void ui_event_BtnSecond(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_WeatherScreen, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_WeatherScreen_screen_init);
        set_daily_information(e);
    }
}
void ui_event_BtnThird(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_WeatherScreen, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_WeatherScreen_screen_init);
        set_daily_information(e);
    }
}
void ui_event_SetLocalScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        local_screen_init(e);
    }
}
void ui_event_BtnBack1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_TaLocal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_KeybLocal,  ui_TaLocal);
        _ui_flag_modify(ui_KeybLocal, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeybLocal, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_BtnSearchCity(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        btn_search_city(e);
    }
}
void ui_event_BtnSearch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        set_city_setting1(e);
    }
}
void ui_event_BtnSearch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        set_city_setting2(e);
    }
}
void ui_event_SetWifiScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        set_wifi_list(e);
    }
}
void ui_event_BtnBack2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_BtnRefreshWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        refresh_wifi_list(e);
    }
}
void ui_event_TaWifiPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TaWifiPassword);
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_SwiWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        set_wifi_status_img(e);
    }
}
void ui_event_BtnBack4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_MainScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_SetLocalScreen_screen_init();
    ui_SetWifiScreen_screen_init();
    ui_WeatherScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
