// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void init_ui_data(lv_event_t * e);
void set_daily_information(lv_event_t * e);
void local_screen_init(lv_event_t * e);
void btn_search_city(lv_event_t * e);
void set_city_setting1(lv_event_t * e);
void set_city_setting2(lv_event_t * e);
void set_wifi_list(lv_event_t * e);
void refresh_wifi_list(lv_event_t * e);
void set_wifi_status_img(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
